name: Terraform

on:
  push:
    branches:
      - main   
  pull_request:
    branches:
      - main   

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Run Terraform Plan with parallelism
    - name: Terraform Plan
      run: terraform plan -out=tfplan -parallelism=10
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

    # Run Terraform Apply with parallelism
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan -parallelism=10
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

