name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.5.0"

      # Cache Terraform providers
      - name: Cache Terraform providers
        uses: actions/cache@v3
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Run Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          TF_VAR_azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}  # Add SSH Public Key

      # Run Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          TF_VAR_azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}  # Add SSH Public Key

